### ISSUE TITLE
Memory leak and/or file descriptor leak in xmp_load_module_from_file

### ISSUE THREAD

**Issue by AliceLR** [cmatsuoka/libxmp#167]
The function `xmp_load_module_from_file` takes a file pointer and loads a module from that file pointer, but it does this in a way that I've found to cause portability issues. This function also necessarily causes memory leaks.

`xmp_load_module_from_file` creates a file pointer from the file descriptor of the provided file pointer [at line 581 of load.c](https://github.com/cmatsuoka/libxmp/blob/master/src/load.c#L581). This allocates a separate file pointer from the user-provided pointer given to the function, which is then closed by `hio_close` [at line 364 of hio.c](https://github.com/cmatsuoka/libxmp/blob/master/src/hio.c#L364). When this file pointer is closed, the file descriptor shared between it and the user file pointer is also closed, meaning the user file pointer can not be safely closed and thus not safely freed.

The intention of duplicating the file pointer in the first place seems to be to avoid closing the user provided file pointer, but that is explicitly not how fdopen works. Note this line from [the fdopen manpage](https://linux.die.net/man/3/fdopen):
> The file descriptor is not dup'ed, and will be closed when the stream created by fdopen() is closed.

In the case of MSVC/MinGW/MacOS, the file descriptor is released but the OS still seems to think it's leaking file descriptors, which will eventually break file IO. I think removing the usage of fdopen in `xmp_load_module_from_file` and making `HIO_HANDLE *`s created by `hio_open_file` not close the file pointer on `hio_close` would be closer to the intended behavior.

**Comment by Spectere** [comment]
To elaborate a bit further on this issue, on macOS we determined that Apple's libc uses reference counting to track the number of used descriptors for both `fopen` and `fdopen` calls, causing the counter to increment by two with every file operation but only decrement by one when `fclose` is called. This would cause the system to think that it ran out of file descriptors after 252 operations (252 + stdin + stdout + stderr = 255, plus two more references would bring it to macOS's limit of 256).

Here are links to the four offending pieces of code in Darwin's libc: [findfp.c](https://opensource.apple.com/source/Libc/Libc-1353.60.8/stdio/FreeBSD/findfp.c.auto.html), [fdopen.c](https://opensource.apple.com/source/Libc/Libc-1353.60.8/stdio/FreeBSD/fdopen.c.auto.html), [fopen.c](https://opensource.apple.com/source/Libc/Libc-1353.60.8/stdio/FreeBSD/fopen.c.auto.html), and [fclose.c](https://opensource.apple.com/source/Libc/Libc-1353.60.8/stdio/FreeBSD/fclose.c.auto.html). Both `fdopen` and `fopen` call the `__sfp` in `findfp.c`, but since `fclose` only calls `__sfprelease` if the handle is valid, the reference counter will only ever be decremented once.

While we don't have the source available for Microsoft's libc implementation, we assume that it behaves in a similar fashion. It bombs after 508 operations, and if you follow the same math as above it brings you up to over 512 descriptors, which is the default limit in Windows. Raising or lowering the limit with Microsoft's `_setmaxstdio` call will raise and lower the number of times that files can be opened and closed in this manner.

**Comment by AliceLR** [comment]
This was fixed by #178, closing.
