### ISSUE TITLE
Tempo issue with a specific MED file

### ISSUE THREAD

**Issue by cspiegel** [cmatsuoka/libxmp#23]
The MED “To Live Is To Die” from [this page](http://amp.dascene.net/detail.php?detail=modules&view=1532) plays at a faster tempo (around 2×) than it does with libmikmod/libmodplug players.

**Comment by cmatsuoka** [comment]
The reason for the tempo error is that this MED uses a BPM value below the minimum established in xmp,h. It's easy to fix by changing XMP_MIN_BPM from 20 to 10, but that change doubles the value of XMP_MAX_FRAMESIZE, and that can crash applications compiled against the current version of the library if they use that macro to allocate buffers. I'll see if we can fix this in a compatible way, otherwise we'll have to wait until the next minor version to add a versioned symbol.

**Comment by cmatsuoka** [comment]
Fixed. MED BPMs use a different time factor than standard tracker modules, so no change to the minimum value was needed (and binary compatibility was maintained). The fix will be available in the next release.
