### ISSUE TITLE
Will you consider MIDI and SF2 support?

### ISSUE THREAD

**Issue by RyanBram** [cmatsuoka/libxmp#25]
MIDI and module format are relatively same in design and implementation although MIDI doesn't provide is own instrument bank.
If this feature is implemented in libxmp, there is no need for separate solution for playing both format.

**Comment by cmatsuoka** [comment]
We need something structurally similar to classic soundtracker modules to
use the current player infrastructure. That means events grouped in tracks,
tracks organized in rows, tracks grouped in patterns, and a single sequence
of patterns. Tracks can be mapped to one or more channels. MIDI fails in
the track rows, patterns and sequence of patterns -- it's a single stream
of events not quantized by row. There are other formats that are not
supported because they don't fit in the soundtracker structure, like TFMX
(each track/channel is sequenced independently). MED is only partially
supported because it can have multiple songs per module and we support only
a single sequence.

**Comment by RyanBram** [comment]
Hi, Mr. Matsuoka,
Thanks for detailed explanation. your argument is reasonable for not supporting Standard Midi Files.

However please allow me to show you some kind of proof of concept that if supporting both MIDI and Module format are possible.

The following is a link of freeware tracker called **BeRo Tracker Classic** created by Benjamin Rosseaux.

http://www.berotracker.de/downloads/

By using that software you can import your Standard MIDI Files (.mid) and exporting it as Impulse Tracker format (.it). You can compare by yourself that the conversion is almost perfect and even you can reopen the output .it file and exporting it back as .mid without loss of quality.

I am really curious to hear your feedback.

Best regards,
RyanBram

**Comment by cmatsuoka** [comment]
Interesting utility, I'll have a look!

**Comment by RyanBram** [comment]
Thank you Mr. Matsuoka for your response.

My intention for requesting Standard MIDI File (.mid) support is for narrowing the gap between MIDI and Module music format. Isn't it cool if we can use sequencer or piano roll for creating music, but exporting the result as Module or we can use tracker for creating music and export it as Standard MIDI File.

Best regards,
RyanBram

**Comment by sagamusix** [comment]
Naturally it's your decision but I'd recommend to close this issue and point people who want MIDI playback to existing solutions such as timidity or FluidSynth. Beating MIDI into a tracker playback library is an unnecessary effort that is impossible to get right. MIDI import only exists in trackers so that people can interchange music data (e.g. for remixes) with other software. Module playback libraries should not be MIDI playback libraries.

**Comment by cmatsuoka** [comment]
Yep, I agree. I was surprised that Benjamin was able to do that in the first place. The roadmap ahead goes more in the line of improving support for existing formats rather than adding more stuff, and then fixing the API for 5.0 to remove hacks.
