### ISSUE TITLE
XMP or libxmp? Link to official site? List of players using libxmp and promote support for it?

### ISSUE THREAD

**Issue by timofonic** [cmatsuoka/libxmp#47]
Hello.

I love to hear chiptunes. Many people see me as a weirdo, but it's the music that makes me focus while doing something and improve my mood, despite I found most people have headaches with them.

I also would love to see this project more known. I find there's a lack of players supporting libxmp. I also have Android devices and I'm unable to find a proper player with wide format support and using libxmp for the chiptunes..

Are there some possibility to have some PR about XMP/libxmp (what name to choose?)? What about a list of players using libxmp?

Are you going to host the official site at SourceForge (certain ad blockers and antivirus tag it as virus)? If yes, what about putting a link here too?

Are there any hopes to make the situation change?

I appreciate a lot your efforts, but it's sad this great project is a lonely cowboy programmer effort :(

Kind regards.

**Comment by cmatsuoka** [comment]
I think we're in a small niche. I think the best way to gain adoption is to have replayer quality, a permissive license and a reasonable API. Also a better name could help, but it's not essential, so let's go to the other points:

- *Quality:* Accuracy-wise, your best choice now is probably OpenMPT because it implements many format quirks that xmp doesn't implement yet (but we're slowly getting there). Before getting adoption, it's better to implement missing features and fix known bugs. We have a lot of them. Code quality was improved a lot in recent iterations with more regression tests, fuzz tests and addressing Coverity Scan warnings. Also there are many ugly points there, especially regarding error handling in the format loaders. Some of them are result of incremental fixes in a 20 year old codebase, but that can (hopefully) be fixed along the way. A total rewrite would be great, but it's not really feasible at this point. Anyway, ugly code is not visible for the library user.

- *Permissive license:* the full player is currently LGPL, and that's not good. The core player is MIT-licensed, which is better for third parties, but certain decompressors and the OPL2 emulator make the entire package to be LGPL. The "lite" version of the library, however, is MIT and can be embedded or statically linked without licensing issues (but only support the more important formats).

- *Reasonable API:* it started as a simple and straighforward API, but new calls were added in recent versions. It's not all that bad, and a revised 5.0 API probably won't be much different.

So I believe the main problem now is replayer quality. If you have the best player, people will use it. Until then, PR won't help: users and developers will quickly notice that certain modules are not playing correctly, and will start bashing the library (and rightfully so).

A brief story about the name: originally (circa 1996) the player was a single executable called xmp (XM Player), which played XM files using the Gravis Ultrasound through the OSS sequencer interface in Linux. It followed a first attempt to write a DOS/Sound Blaster mod player called MPH (Hipolito's Mod Player). Later support for more formats (and software mixing) was added, but the name was not changed. In release 4.0 the player was split in library (libxmp) and application (xmp).

**Comment by cmatsuoka** [comment]
Release 4.4.0 should be out soon and it vastly improves replayer quality. A few important bugs that were more than 15 years old have been fixed. There's a lot to go yet, but we're on the way to address the quality problem.
