### ISSUE TITLE
Command-line based builds

### ISSUE THREAD

**Issue by Guichaguri** [cmatsuoka/libxmp#49]
Any plans for command-line based builds?
Similarly to FFmpeg, it should be able to pipe a raw stream to stdin and output a PCM stream to stdout.
It will be useful for using this library in other languages (like in Node.js)

**Comment by cmatsuoka** [comment]
Module formats are not streamable (in the classic sense) because the reader needs the entire input file to be in memory before it starts rendering the output (and we can't load the module directly from the input stream because many formats need a seekable input). We could, however, simulate it by reading the entire module from stdin, store it in memory, and then read it using [xmp_read_module_from_memory()](http://xmp.sourceforge.net/libxmp.html#int-xmp-load-module-from-memory-xmp-context-c-void-mem-long-size). If that's good enough, it should be very easy to do with the current library.

**Comment by Guichaguri** [comment]
That is not bad at all, I don't care about reading the entire module

**Comment by cmatsuoka** [comment]
Then [this example](http://xmp.sourceforge.net/libxmp.html#a-simple-example) should work for you. Just change it to read the input file from stdin into a buffer and load from the buffer instead of loading directly from the file. I'll have to use this same strategy to load from Google Drive in the Android application.

**Comment by Guichaguri** [comment]
Thank you

**Comment by cmatsuoka** [comment]
You're welcome, please let me know if it doesn't work so I can fix the library accordingly.
