### ISSUE TITLE
Not detecting submodule correctly

### ISSUE THREAD

**Issue by knight-ryu12** [cmatsuoka/libxmp#51]
I put this Issue on xmp-cil. But I think that repo is wrong for it.

To be sure, I have this tune and played on xmp.
[](http://modarchive.org/index.php?request=view_by_moduleid&query=59854)
It has 3 submodule in it(Checked with Schismtracker)
But in xmp, it is not detecting correctly.(only 2 appears)

**Comment by knight-ryu12** [comment]
O.o link gone
http://modarchive.org/index.php?request=view_by_moduleid&query=59854

**Comment by cmatsuoka** [comment]
Oops. The S3M reading routine was trying to determine the number of patterns in the module by checking the highest pattern number until the first 0xff marker instead of just using the number of patterns supplied in the file header.

If I use the header value, we get:

Loading WHEN.S3M (1 of 1)
Module name  : When the heavens fall
Module type  : Scream Tracker 3.03 S3M
Module length: 54 patterns
Patterns     : 56
Instruments  : 26
Samples      : 26
Channels     : 13 [ 3 c 3 c 3 c 3 c 3 c 3 c 3 ]
Duration     : 5min29s (main sequence)
               0min30s (sequence 1 at position 2B)
               0min15s (sequence 2 at position 30)
               0min15s (sequence 3 at position 33)

Fix will be in the next release.

**Comment by cmatsuoka** [comment]
Additional note: it seems that we can't just trust the header. I'm fixing the detection routine approprately.

**Comment by knight-ryu12** [comment]
ok
