### ISSUE TITLE
MED synth instruments broken

### ISSUE THREAD

**Issue by cmatsuoka** [cmatsuoka/libxmp#67]
MED synth instruments using multiple samples are not being correctly looped. This is probably caused by the mixer and anticlick refactoring in 4.4.0.

**Comment by TEOL85** [comment]
I signed up to report this one. Already done by the looks of things. 

To me in my heaadphones it sounds more like an issue of a channels missing thing as MED could go up to 8 or 16 samples but libxmp only supports 4 channels of the format.

I find the issue is most prominent in this track: http://amp.dascene.net/downmod.php?index=88793 

And heres the real music disk of it to compare: http://cbm8bit.com/amiga/amiga/search?query=C.+Jermy+Music+II+%281992%29%28Carl+Jermy%29.zip

Big difference and it's mainly channel issues I think.

**Comment by cmatsuoka** [comment]
The original problem I reported was caused by the mixer anticlick, but there's something else going wrong with the module you posted and that must be fixed as well:

```
05                                  [05] 01588 00000 00000  V40 +000 +36 P80
06                                  [06] 01588 00000 00000  V40 +000 +36 P80
07                                  [07] ffffffff 00000 022b2L V40 +000 +36 P80
08                                  [08] ffffffff 008c8 009c8L V40 +000 +36 P80
09                                  [09] 02325 00000 00000  V28 +000 +36 P80
0a                                  [0a] ffffffff 07410 07e4aL V40 +000 +36 P80
0b                                  [0b] ffffffff 00000 026a8L V40 +000 +36 P80
0c                                  [0c] 016a2 000b8 016a2L V20 +000 +36 P80
```

**Comment by TEOL85** [comment]
Lemmings 2 don't quite sound right neither so it's in general that MED has issues with channels missing. Thats due to Octimed the program for making them as the name suggests being 8 channels to program the music into the 4 of the Paula but to play it back properly the player has to have 8 channels for MED mode I think but I don't know really i'm just a guesser.

**Comment by mldoering** [comment]
Am Tue, 23 Aug 2016 03:22:16 -0700
schrieb TEOL85 <notifications@github.com>:

> Lemmings 2 don't quite sound right neither so it's in general that
> MED has issues with channels missing. Thats due to Octimed the
> program for making them as the name suggests being 8 channels to
> program the music into the 4 of the Paula but to play it back
> properly the player has to have 8 channels for MED mode I think but I
> don't know really i'm just a guesser.
> 

The maintune? The maintune is tricky. It is a genuine 4ch octamed med.

But it does play differently on different players. On a stock Amiga
Paula player the extended octave range is missing which is supported by
the softmixing by e.g. Octamed studio. 
However the game did use the hardware 4ch player routine, thus
limiting the octave range the the Amiga hardware limits.

I could provide an (emulated) ogg of the maintune of the two tribes as
reference.




---
Digital unterschrieben mit GNU Privacy Guard
Fingerabdruck: 330F 99EE 65A7 DF35 BF20  B5DC A0DC 8F02 5B1E CC24

**Comment by cmatsuoka** [comment]
That could be interesting Michael, so a switch could be added to play as Paula would or using the extended range. I presume the game player uses Paula octaves and ignores the extended range?

**Comment by mldoering** [comment]
Am Sat, 27 Aug 2016 16:49:20 -0700
schrieb Claudio Matsuoka <notifications@github.com>:

> That could be interesting Michael, so a switch could be added to play
> as Paula would or using the extended range. I presume the game player
> uses Paula octaves and ignores the extended range?
> 

yes.

I put the file online here.
https://app.box.com/s/7vdot6c0t2yaf6l3thl8l9jwdmfeahwg

btw. to a certain extend, the same affects plain mod files. 
4ch Fasttracker uses a wider octave range than plain 4ch mods
(Pro/Noise/Star) and sound differently with Paula instead of
a softmixing routine and vice versa. 


---
Digital unterschrieben mit GNU Privacy Guard
Fingerabdruck: 330F 99EE 65A7 DF35 BF20  B5DC A0DC 8F02 5B1E CC24

**Comment by TEOL85** [comment]
The UADE example sounds exactly like the real AMIGA definitely.

**Comment by cmatsuoka** [comment]
Ok, this one will be trickier to handle than I originally thought, so I'll add a new issue and close this one since the (horribly) broken synth instruments are fixed.
