### ISSUE TITLE
IT/S3M "len" and "pat" members of xmp_module set incorrectly.

### ISSUE THREAD

**Issue by NoSuck** [cmatsuoka/libxmp#75]
I have yet to discern much of a pattern, but xmp_module_info->mod->len is one or two too many in most cases (i.e. the real order length for the S3M below is 44, but libxmp sets the length to 46):

https://modarchive.org/index.php?request=view_by_moduleid&query=72440

xmp_module_info->mod->pat, meanwhile, goes the other direction.  It is set to 49 when it should be 50.  Does anyone know what's going on?  I'm not familiar enough with the loaders yet to provide much help.

I discovered this issue after using pat/len to iterate over patterns/order, only to run into segfaults!

**Comment by sagamusix** [comment]
The order list of IT/S3M files may contain additional "---" patterns at the end. In particular, the order list in S3M files needs to have an even length (otherwise ST3 will cut off the last pattern). The order list in that module really is 46 items long, but the last two are "---" patterns (pattern number is 255). Did you maybe try to read the pattern contents of this non-existing pattern?

**Comment by cmatsuoka** [comment]
Saga is correct, pattern numbers 254 and 255 in IT and S3M are marker codes instead of real patterns. When QUIRK_MARKER is set, you shouldn't try to read their contents.

**Comment by cmatsuoka** [comment]
I'm closing this, please reopen if you think this is a real bug not related to the explanation above.
